### ISSUE TITLE
scpc error: missing reference file for charge density 

### ISSUE THREAD

**Issue by boyguyue** [aradi/SCPC-Method#10]
Dear developers:
I am now learning SCPC, but there are some problems with my test.
For the SCPC calculation, I offered uncorrected charged WAVECAR and CHGCAR by default vasp6.2. 
However, the SCPC cannot work with an error:
_" scpc error: missing reference file for charge density                   |
|                                                                             |
|       ---->  I REFUSE TO CONTINUE WITH THIS SICK JOB ... BYE!!! <----  "_

How can I solve this problem?
Many Thanks！
Yue Gu

**Comment by isobestico** [comment]
Hi, 

 The error is pointing out that there is no REFCHG file ( the charge file for reference system - neutral defect or pristine ). To use the SCPC model you must provide the charge and the potential files (REFCHG and REFPOT) for a  reference system which could be get from a pristine system (without any defect) or from a neutral defect system. So in your execution, you missed providing REFCHG and REFPOT files for the reference system.

**Comment by boyguyue** [comment]
Thanks for your reply!
Now, I copy the CHGCAR/POTCAR of pristine system to REFCHG/REFPOT in SCPC directory，but there is another error:
"forrtl: severe (59): list-directed I/O syntax error, unit 213, file /share/home/WORKSPACE/test/scf/REFPOT"
Does this error come from incorrect settings or bad compilation?

**Comment by isobestico** [comment]
Hi, 

    I don´t have any clue about this error coming from. It seems you have some error inside the file REFPOT or something is not reading well this file. Are you getting the same error with one of our examples? Is it one of our examples?

**Comment by isobestico** [comment]
Please send me your INCAR for the defect and for the pristine, 
probably ran the calculation with different ENCUT values. Then
the expected grid size for the files is wrong or your POTCAR file 
from the pristine is corrupted!

**Comment by boyguyue** [comment]
I guess there may be a problem with my POTCAR format. For details, please see the attachment.
[test.zip](https://github.com/aradi/SCPC-Method/files/10565698/test.zip)

**Comment by isobestico** [comment]
Hi, 

    I have some points to address:

(1) in your zip file, both structures are the same - really identical. SCPC will not work properly for ionized states, I have never tested this situation. I have only used SCPC method in substitutional charged defect or vacancy charged defects. You are only removing/adding electrons to the pristine system - SCPC will fail on this. 

(2) you also did not pay attention to our recommendations about the unit cell sizes. The SCPC method will fail due to numerical issue for small unit cell like yours. Your A and B lengths are too small (A=5 and B=9). You should use something close to 15 - 20 Angstrom for the lateral sizes (A and B). For the C direction, probably you will need to enlarger too, I am using around 15A for the vacuum or 2-3 times the thickness of the slab.  Please read again the recommendation section (sec 2)
https://github.com/aradi/SCPC-Method/tree/main/VASP

(3) before running your example, you should run some of our small/toy tests to check your compilation.
