### ISSUE TITLE
Segmentation fault while running examples 

### ISSUE THREAD

**Issue by siddarthachar** [aradi/SCPC-Method#14]
Hi, I am trying to run SCPC calculations for the `vcl-nacl-slab` example provided in this GitHub repo. I am encountering segmentation fault errors `forrtl: severe (174): SIGSEGV, segmentation fault occurred` when I tried to run this example. I used VASP 6.3.2, which was compiled with intel/2017.1.132 and intel-mpi/2017.1.132. These calculations were run on MPI. Is there a bug in the code. Are there patches that can fix this? Here's part of the VASP error report printed out. 

```
 LDA part: xc-table for Pade appr. of Perdew
 found WAVECAR, reading the header
  number of bands has changed, file:   428 present:   432
  trying to continue reading WAVECAR, but it might fail
 POSCAR, INCAR and KPOINTS ok, starting setup
 FFT: planning ... GRIDC
 FFT: planning ... GRID_SOFT
 FFT: planning ... GRID
 reading WAVECAR
 random initialization beyond band          428
 the WAVECAR file was read successfully
 charge-density read from file: unknown                                 
 magnetization density read from file 1
 entering main loop
       N       E                     dE             d eps       ncg     rms          rms(c)
forrtl: severe (174): SIGSEGV, segmentation fault occurred
```

I modified the INCAR file to match the SCPC tags corresponding to version 6+. Here's the INCAR file: 
```

  ICHARG = 1 ; charge guess (2) orbital superposition   (1) read charge     (11) non-scf

  NPAR = 2 ;

  LWAVE  = F ; write WAVECAR
  LCHARG = F ; write CHGCAR

  GGA = PE ;

  ISPIN = 2 ;
  NELECT = 568.00

  LREAL = Auto ;

  ENCUT = 150.00 ;

# Ionic Relax.
  IBRION = -1 ; conjugate gradient
  ISIF   =  0 ; opt lattice and ion positions
  NSW    =  0 ; num. step ion relax.

# DOS 
  ISMEAR = 0    ; (0) gaussian for relax ion     (1) metal    (-5) insulator/semiconductor dos
  SIGMA  = 0.05 ; (0.2) metal      (0.05) insulator/semiconductor

# self-consistent charge-potential correction - SCCVCor
#  DOVCOR   = T    ;
#  INVCOR   = 1    ;
#  VCQTOT   = 1.0  ;
#  VCZLOW   = 0.22 ;
#  VCZHIG   = 0.53 ;
#  VCDIEL   = 2.46 ;
#  VCBROAD  = 0.40 ;

SCPC {
    USE   = T    ; turning on the SCPC method
    IN    = 1    ; starting on the first cycles
    QTOT  = 1.00 ; formal defect charge
    ZLOW  = 0.22 ; lower interface boundary
    ZHIG  = 0.53 ; upper interface boundary
    DIEL  = 2.46 ; macroscopic dielectric
    BROAD = 0.40 ; broadening for the interface
    PRTX  = T    ; printing the averages on the X direction
    #    RXCUT = 0.1  ; damping region on X direction for the model charge
    #    RYCUT = 0.1  ;
    }
```
This SCPC compiled version of VASP 6.3.2 does work fine when the SCPC method is not enabled.

**Comment by isobestico** [comment]
Hello, 

   I am not sure if you are using the last version of SCPC release, so I will invite you to send me an email in my professional email at Univ. Lorraine. Please check the original paper for getting my prof. EMail. 

  However, I am not sure that this issue is related to the correction patch (high dielectric constant value). For those examples I used a POTCAR with 7 electrons to the Cl and 1 electron to the Na, I guess. Check if you are using the right POTCAR file to match the defect generated by NELECT value. NEUTRAL defect NELECT = 71*7 + 72 = 569, so for CHARGED system ==> NELECT = 568. 

  Furthermore, please check your installation you mention that the SCPC compiled version is not working well if you don't enable the SCPC method - this shouldn't happen. Moreover, also I will recommend using the external libraries for the Poisson and isolating potentials that will be together with the patch of release 7.2 in vasp-6.2 (send an email to me to get this).
