### ISSUE TITLE
the spin-orbit coupling with SCPC-method

### ISSUE THREAD

**Issue by wangxx12311** [aradi/SCPC-Method#6]
Dear,teacher, I discovered that the calculation with spin-orbit coupling (SOC) cannot continue when using SCPC-method. There are not any output result in self-consistent calculation. That is the first SCPC step can't appear. I want to know whether this SCPC-method can be applied in spin-orbit coupling. If not, how should I go about calculating the materials with SOC? I used the vasp-6.2.0 version and other calculations without SOC can go on normally.  I am looking forward to your reply. Best wishes to you.

**Comment by isobestico** [comment]
Hello, 
Unfortunately, there is some issue with SCPC and SOC, you cannot use it together with vasp_ncl version. 

This issue was already reported before by other users and it is in our GitHub warnings

https://github.com/aradi/SCPC-Method/tree/main/VASP/warning-issues-bugs

[ Mar.15.2021] The SCPC cannot be used with the non-collinear keyword. The vasp_ncl with SCPC is broken. By the moment, you cannot use non-collinear magnetization. The authors thank to Jing Zhan and prof. Dr. Qihang Liu from the Southern Univ. of Science and Technology of Shenzhen/China for their contribution on reporting the bug/issue with the non-collinear version of SCPC.
